### ISSUE TITLE
Kakao login 지원

### ISSUE THREAD

**Issue by jajaspider** [jajaspider/rainbow_gift#1]
카카오 소셜 로그인을 이용합니다.

passport-kakao, express-session

**Comment by hahyeonsook** [comment]
1. 카카오 로그인(1차), 구글 및 기타 SNS 회원가입, 로그인, 로그아웃, 탈퇴, 보기
    1. 카카오 로그인으로 구현 → 추후에 이슈있으면 수정
    2. CRUD (탈퇴시 즉시 삭제)
    3. access token, refresh token
        1. **인증 서비스**를 따로 두고 인증 서비스를 지난 후에 서버 앱에 들어오도록
        2. 구현이 어떤 걸로 되어있나? 언어? 툴? 시스템이든?
        3. redis + nodejs (express)

**Comment by jajaspider** [comment]
신규 프로젝트로 전환
