### ISSUE TITLE
AdminLTE3 템플릿 및 Vue 적용

### ISSUE THREAD

**Issue by jajaspider** [jajaspider/rainbow_gift#3]
AdminLTE3 템플릿을 사용하고, Vue가 적용된 서버페이지를 구성합니다.

reference: https://github.com/ColorlibHQ/AdminLTE, https://adminlte.io/themes/v3/

**Comment by jajaspider** [comment]
기프티콘 리스트를 보여주고, 기프티콘을 등록하는 페이지까지 연결될 예정입니다.

기프티콘 등록페이지는 추후, modal이 지원될 때 변경될 예정입니다.

이후 기능 구현 issue는 따로 작성합니다.

**Comment by hahyeonsook** [comment]
2. gifticon 저장, 삭제, 보기
    1. gifticon , 이미지(option), 사용기간(option), 바코드(required), 추가 번호(option), 기프티콘 이름(required) 등 입력 form 제공
    2. 수기입력
    3. CRUD
        1. 상세보기 클릭했을 때, 이미지를 띄워줌
    4. 상태변경 api

**Comment by jajaspider** [comment]
새로운 이슈에서 대응합니다.
